services:
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapy_container
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=scrapydb
      - DB_USER=scrapyuser
      - DB_PASSWORD=scrapypassword

  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: scrapyuser
      POSTGRES_PASSWORD: scrapypassword
      POSTGRES_DB: scrapydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
